### ISSUE TITLE
parts list and instructions for making the MAGI

### ISSUE THREAD

**Issue by nick-youngblut** [dvuono/MAGI#1]
The MAGI looks like a very useful tool for microbiologists. Thanks for creating & validating it!

In order to fully reproduce [your published work](https://doi.org/10.3389/fmicb.2019.01135), it would be helpful to have a full list of parts for the MAGI and a set of instructions on how to construct it. I didn't see either provided with the [manuscript](https://doi.org/10.3389/fmicb.2019.01135), and it seems that this repo only includes the software required for the MAGI.

**Comment by dvuono** [comment]
Hi Nick,
Thanks for taking interest in our MAGI device. You are correct, this repo is only for the software to run MAGI. Our manuscript was submitted as a technology report to showcase the technology, supported by the conflict of interest statement to sell it. Thus the experiments can be reproduced by purchasing the instrument. I would be happy to answer any questions you might have and provide you with a quote for an instrument. We are currently manufacturing 12 channel MAGI's, as presented in the manuscript. Some of the latest design upgrades include a new raspberry pi with WiFi, integrated power supply, and hardware enclosure, keyed ribbon cable connectors, and upgraded software. Feel free to email me at dvuono@gmail.com
